apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rcon-web-admin-http
  namespace: traefik
spec:
  parentRefs:
    - name: traefik
      sectionName: http-rcon         # listener name in the Gateway
  rules:
    - backendRefs:
        - name: rcon-web-admin
          namespace: rcon-web-admin
          port: 80

